@startuml
class Product {
    -id: int
    -name: String
    -qty: int
    -unitPrice: double
    +getId(): int
    +getName(): String
    +getQty(): int
    +getUnitPrice(): double
    +calculateTotal(): double
}

@enduml